# Generated by Django 4.0.2 on 2022-02-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userconsent_consent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsent',
            name='fi_date_range_from',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='fi_date_range_to',
        ),
    ]
