# Generated by Django 4.0.2 on 2022-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userconsent_fi_date_range_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
